name = "emailviewer"
main = "src/worker.ts"
compatibility_date = "2024-02-23"

[[d1_databases]]
binding = "readDB"
database_name = "megawati"
database_id = "fec02396-4d66-421d-9bf1-b666279443bb"

[[d1_databases]]
binding = "readAkun"
database_name = "akun"
database_id = "02c2bae0-05c2-44d6-9530-cde89fa9850c"

[observability.logs]
enabled = true